### ISSUE TITLE
Load the /space route by default

### ISSUE THREAD

**Issue by ReadyPlayer2** [ReadyPlayer2/nasa-playgrounds#13]
This will make it easier to develop.

Info:
Currently when running the application using `npm start` the URL `localhost:3000/` is loaded with the default create-react-app page. This page is useful in debugging (to check routes are working etc), but is rarely required so it would be better to load directly to `localhost:3000/space`.

**Comment by candacej97** [comment]
Hi 👋🏾 I'd like to help out on some of the easier things that you may not have time for. I've worked with React and JavaScript before. However, I'm unclear as what you mean by routing to /space by default.

Would you not want / to be seen at all? I could submit a pull request for a simple redirect!

**Comment by ReadyPlayer2** [comment]
According to [this PR](https://github.com/facebook/create-react-app/issues/2959) this feature is not available yet =/
